---
title: "Guanaco F2025"
author: "Sophie Pentz"
date: "2025-11-16"
output: output: word_document
---

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(janitor)
library(readxl)
library(scales)
library(ggrepel)
library(forcats)
library(stringr)
```

```{r}
guanaco <- read_excel(
  "2025.12.06_Guanaco_Master_Sheet.xlsx",
  col_types = c(
    rep("guess", 10),  # first 10 columns
    "text",            # column 11 (date/time column)
    rep("guess", 19)   # remaining columns
  )
)
```

```{r}
guanaco_clean <- guanaco %>%
  filter(
    !is.na(`Animal spp`),         
    !is.na(`Chilean Seasson`)
  ) %>%
  mutate(
    Year = as.numeric(Year),
    km = as.numeric(`2024 Total Transect Length`),
    animal_group = if_else(`Animal spp` == "Guanaco",
                           "Guanaco",
                           "Livestock")
  ) %>%
  filter(
    !is.na(Year),
    !Year %in% c(2026, 2027)
  )
```

```{r}
# SUMMARIZE FOR BARS: counts by year + season
guanaco_clean <- guanaco_clean %>%
  filter(!is.na(`Animal spp`)) %>%     
  mutate(
    animal_group = if_else(`Animal spp` == "Guanaco",
                           "Guanaco",
                           "Livestock")
  )
```

```{r}
# SUMMARIZE FOR LINE: km per year
guanaco_km <- guanaco_clean %>%
  group_by(Year) %>%
  summarise(total_km = sum(km, na.rm = TRUE), .groups = "drop")

guanaco_counts <- guanaco_clean %>%
  group_by(Year, `Chilean Seasson`, animal_group) %>%
  summarise(
    total_count = sum(`TOTAL COUNT`, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  complete(
    Year,
    `Chilean Seasson`,
    animal_group,
    fill = list(total_count = 0)
  ) %>%
  filter(!is.na(animal_group)) 
```


```{r}
scale_factor <- max(guanaco_counts$total_count) / max(guanaco_km$total_km)
```

```{r}
guanaco_counts <- guanaco_counts %>%
  mutate(
    `Chilean Seasson` = fct_relevel(
      str_trim(str_to_title(`Chilean Seasson`)),
      "Summer",
      "Spring"
    ),
    animal_group = fct_relevel(
      animal_group,
      "Livestock",
      "Guanaco"
    )
  )
```


```{r}
pop_plot <- ggplot() +
  
  # BAR GRAPH
  geom_col(
  data = guanaco_counts,
  aes(
    x = factor(Year),
    y = total_count,
    fill = `Chilean Seasson`
  ),
  position = position_dodge(width = 0.7),
  width = 0.55
) +

  # TEXT LABELS ON TOP OF BARS
 geom_text(
  data = guanaco_counts %>% filter(total_count > 0),
  aes(
    x = factor(Year),
    y = total_count,
    label = total_count,
    group = `Chilean Seasson`
  ),
  position = position_dodge(width = 0.7),
  vjust = -0.5,
  size = 3
) +

  # KM LINE (scaled)
  geom_line(
    data = guanaco_km,
    aes(x = factor(Year), y = total_km * scale_factor, group = 1),
    color = "black",
    linetype = "dotted",
    linewidth = 1
  ) +
  geom_point(
    data = guanaco_km,
    aes(x = factor(Year), y = total_km * scale_factor),
    color = "black",
    size = 2
  ) +

  scale_y_continuous(
    name = "Total Guanaco Count",
    sec.axis = sec_axis(~ . / scale_factor, name = "Total Kilometers Tracked")
  ) +
  facet_wrap(~ animal_group, ncol = 1, scales = "free_y") +
  labs(
    title = "Guanaco Count by Year and Season + Total Kilometers Tracked",
    x = "Year",
    fill = "Chilean Season"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        panel.spacing = unit(1.2, "lines"),
        plot.margin = margin(10, 10, 10, 10), 
        panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
ggsave(
  filename = "guanaco_plot.png",
  plot = pop_plot,
  width = 12,    
  height = 9,    
  dpi = 300
)
```

```{r}
guanaco_age <- guanaco_clean |>
  filter(`Animal spp` == "Guanaco") |>
  select(
    Year,
    `Chilean Seasson`,
    Adult_M,
    Adult_F,
    Adult_unk,
    Subadult_M,
    Subadult_F,
    `Juvenile(Chulengo)`,
    Undetermined_individuals
  )
```

```{r}
guanaco_age_long <- guanaco_age |>
  pivot_longer(
    cols = c(
      Adult_M,
      Adult_F,
      Adult_unk,
      Subadult_M,
      Subadult_F,
      `Juvenile(Chulengo)`,
      Undetermined_individuals
    ),
    names_to = "raw_class",
    values_to = "count"
  ) |>
  filter(!is.na(count), count > 0) |>
  mutate(
    age_class = case_when(
      raw_class %in% c("Adult_M", "Adult_F", "Adult_unk") ~ "Adult",
      raw_class %in% c("Subadult_M", "Subadult_F") ~ "Subadult",
      raw_class == "Juvenile(Chulengo)" ~ "Chulengo",
      raw_class == "Undetermined_individuals" ~ "Undetermined"
    )
  )

age_summary <- guanaco_age_long |>
  group_by(age_class) |>
  summarise(total_count = sum(count), .groups = "drop")
```

```{r}
age_year_summary <- guanaco_age_long |>
  group_by(Year, age_class) |>
  summarise(
    total_count = sum(count),
    .groups = "drop"
  )

age_year_summary$age_class <- factor(
  age_year_summary$age_class,
  levels = c("Chulengo", "Subadult", "Adult", "Undetermined")
)
```


```{r}
age_plot <- ggplot(age_year_summary,
       aes(x = factor(Year), y = total_count, fill = age_class)) +
  geom_col(position = "fill") +
  scale_y_continuous(labels = percent_format()) +
  labs(
    title = "Proportional Guanaco Age-Class Structure by Year",
    x = "Year",
    y = "Proportion of Total Population",
    fill = "Age Class"
  ) +
  theme_minimal(base_size = 13)

ggsave(
  filename = "age_plot.png",
  plot = age_plot,
  width = 12,    
  height = 9,    
  dpi = 300
)
```

```{r}
habitat_summary <- guanaco_clean |>
  filter(
    `Animal spp` == "Guanaco",
    !is.na(`Habitat Type`),
    `Habitat Type` != "Unknown"
  ) |>
  group_by(`Habitat Type`) |>
  summarise(total_count = n(), .groups = "drop")
```

```{r}
habitat_summary <- guanaco_clean |>
  filter(
    `Animal spp` == "Guanaco",
    !is.na(`Habitat Type`),
    !(`Habitat Type` %in% c("Unknown", "-", ""))
  ) |>
  group_by(`Habitat Type`) |>
  summarise(total_count = n(), .groups = "drop") |>
  filter(total_count > 0) |>
  mutate(
    pct = total_count / sum(total_count),
    label = scales::percent(pct, accuracy = 1)
  )
```

```{r}
pie_chart <- ggplot(habitat_summary,
       aes(x = "", y = total_count, fill = `Habitat Type`)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text_repel(
    aes(label = label),
    position = position_stack(vjust = 0.5),
    show.legend = FALSE,
    size = 4
  ) +
  labs(
    title = "Guanaco Observations by Habitat Type",
    fill = "Habitat Type"
  ) +
  theme_void()

ggsave(
  filename = "pie_chart.png",
  plot = pie_chart,
  width = 12,    
  height = 9,    
  dpi = 300
)
```

```{r}
habitat_year <- guanaco_clean |>
  filter(
    `Animal spp` == "Guanaco",
    !is.na(`Habitat Type`),
    !(`Habitat Type` %in% c("Unknown", "-", ""))
  ) |>
  group_by(Year, `Habitat Type`) |>
  summarise(total_count = n(), .groups = "drop")
```

```{r}
habitat_year_prop <- habitat_year |>
  group_by(Year) |>
  mutate(
    pct = total_count / sum(total_count)
  ) |>
  ungroup()
```

```{r}
habitat_graph <- ggplot(habitat_year_prop,
       aes(x = factor(Year), y = pct, fill = `Habitat Type`)) +
  geom_col(width = 0.9) +
  scale_y_continuous(labels = percent_format()) +
  labs(
    title = "Proportional Habitat Use of Guanaco by Year",
    x = "Year",
    y = "Percentage of Observations",
    fill = "Habitat Type"
  ) + theme(
  axis.text.x = element_text(angle = 45, hjust = 1)
)

ggsave(
  filename = "habitat_graph.png",
  plot = habitat_graph,
  width = 12,    
  height = 9,    
  dpi = 300
)
```

```{r}
habitat_use <- guanaco_clean |>
  filter(`Animal spp` == "Guanaco") |>
  filter(
    !is.na(`Habitat Type`),
    !(`Habitat Type` %in% c("-", "Unknown"))
  ) |>
  group_by(`Habitat Type`) |>
  summarise(
    use = sum(`TOTAL COUNT`, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    rel_use = use / sum(use, na.rm = TRUE)
  )

```

```{r}
habitat_use_clean <- habitat_use |>
  filter(
    !is.na(rel_use),
    rel_use > 0,
    !is.na(`Habitat Type`)
  )

habitat_use_clean <- habitat_use_clean |>
  arrange(desc(rel_use)) |>
  mutate(`Habitat Type` = factor(`Habitat Type`, levels = `Habitat Type`))

relativeuse_graph <- ggplot(habitat_use_clean,
       aes(x = `Habitat Type`, y = rel_use, fill = `Habitat Type`)) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(labels = percent_format(), limits = c(0, 1)) +
  labs(
    title = "Relative Habitat Use by Guanaco",
    x = "Habitat Type",
    y = "Relative Use (%)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

ggsave(
  filename = "relativeuse_graph.png",
  plot = relativeuse_graph,
  width = 12,    
  height = 9,    
  dpi = 300
)
```
